import eslint from '@eslint/js';
import globals from 'globals';
import i18nextPlugin from 'eslint-plugin-i18next';
import reactPlugin from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'node_modules',
      'dist',
      // Generated by `npm run gen:types` — do not lint.
      'src/**/api-types.ts',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooks,
    },
    settings: {
      react: { version: 'detect' },
    },
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      ...reactPlugin.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off', // react-jsx transform
      'react/prop-types': 'off', // TypeScript covers this
      // eslint-plugin-react-hooks v7 flat config — includes the
      // compiler-era rules (refs, purity, ...) instead of
      // hand-wiring just the two legacy ones.
      ...reactHooks.configs['recommended-latest'].rules,
      'react-hooks/exhaustive-deps': 'warn',
      // These two fire on legitimate existing patterns (syncing
      // props into local state on open; hand-rolled memoization).
      // Kept as warnings until those spots are refactored.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
    },
  },
  {
    // User-facing JSX goes through t()/<Trans> — warn (not error)
    // so legitimate leftovers don't block the build.
    files: ['src/**/*.{tsx,jsx}'],
    ignores: ['**/*.test.{ts,tsx}', 'src/test/**'],
    plugins: { i18next: i18nextPlugin },
    rules: { 'i18next/no-literal-string': 'warn' },
  },
  {
    files: ['**/*.test.{ts,tsx}', 'src/test/**'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
  {
    files: ['*.config.{js,ts}', 'scripts/**/*.mjs'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
);
