# Generated by Django 4.2.6 on 2026-09-25 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_transaction_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='', help_text='Optional hex color, e.g. #0d6efd', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_manual_category',
            field=models.BooleanField(default=False, help_text='Manual override; rules never change this category'),
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('sender_receiver_pattern', models.CharField(blank=True, default='', help_text='Matches debtor or creditor name', max_length=255)),
                ('description_pattern', models.CharField(blank=True, default='', help_text='Matches remittance information', max_length=255)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts with')], default='contains', max_length=20)),
                ('operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', help_text='How the two patterns combine', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category'),
        ),
    ]
