# Generated by Django 4.2.6 on 2026-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category_transaction_is_manual_category_categoryrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrule',
            name='match_type',
            field=models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with')], default='contains', max_length=20),
        ),
    ]
