# Generated by Django 4.2.6 on 2026-09-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_alter_categoryrule_match_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionlimit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transactionlimit',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional: limit only spending in this category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='finance.category'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionlimit',
            unique_together={('account', 'user', 'category')},
        ),
    ]
