# Generated by Django 4.2.6 on 2026-09-25 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_user_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlimit',
            name='alerted_30d_at',
            field=models.DateTimeField(blank=True, help_text='When a push alert was last sent for the 30-day window', null=True),
        ),
        migrations.AddField(
            model_name='transactionlimit',
            name='alerted_7d_at',
            field=models.DateTimeField(blank=True, help_text='When a push alert was last sent for the 7-day window', null=True),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
