# Generated by Django 4.2.6 on 2026-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_transactionlimit_alerted_30d_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_updated_at',
            field=models.DateTimeField(blank=True, help_text='When last_balance was fetched', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_balance',
            field=models.JSONField(blank=True, help_text='Last balance object fetched from GoCardless', null=True),
        ),
    ]
