# Generated by Django 4.2.6 on 2026-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_account_balance_updated_at_account_last_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='additional_data_structured',
            field=models.JSONField(blank=True, help_text='Raw additionalDataStructured (e.g. card instrument)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.JSONField(blank=True, help_text='Raw balanceAfterTransaction object', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_transaction_code',
            field=models.CharField(blank=True, help_text='ISO 20022 code, e.g. PMNT-CCRD-POSD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='end_to_end_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remittance_information_array',
            field=models.JSONField(blank=True, help_text='Raw remittanceInformationUnstructuredArray', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
