# Generated by Django 4.2.6 on 2026-09-29 07:12

from django.db import migrations, models
from django.db.models import F


def copy_match_type_to_description(apps, schema_editor):
    """Old match_type covered both patterns; copy it over."""
    CategoryRule = apps.get_model('finance', 'CategoryRule')
    CategoryRule.objects.update(
        description_match_type=F('counterparty_match_type')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transaction_additional_data_structured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryrule',
            old_name='match_type',
            new_name='counterparty_match_type',
        ),
        migrations.RenameField(
            model_name='categoryrule',
            old_name='sender_receiver_pattern',
            new_name='counterparty_pattern',
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='counterparty_scope',
            field=models.CharField(choices=[('any', 'Debtor or creditor'), ('debtor', 'Debtor (sender)'), ('creditor', 'Creditor (receiver)')], default='any', help_text='Which name field the counterparty pattern matches', max_length=10),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='description_exclusion',
            field=models.CharField(blank=True, default='', help_text='Rule never applies when remittance info contains this', max_length=255),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='description_match_type',
            field=models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with')], default='contains', max_length=20),
        ),
        migrations.RunPython(
            copy_match_type_to_description,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='operator',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', help_text='How the counterparty and description patterns combine', max_length=3),
        ),
    ]
