# Generated by Django 4.2.6 on 2026-09-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_rename_match_type_categoryrule_counterparty_match_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlimit',
            name='alerted_monthly_at',
            field=models.DateTimeField(blank=True, help_text='When a push alert was last sent for the monthly window', null=True),
        ),
        migrations.AddField(
            model_name='transactionlimit',
            name='limit_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limit for the current calendar month', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='counterparty_pattern',
            field=models.CharField(blank=True, default='', help_text='Matches the scoped debtor/creditor name', max_length=255),
        ),
        migrations.CreateModel(
            name='LimitEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='First day of the evaluated calendar month')),
                ('spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='finance.transactionlimit')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('limit', 'period_start')},
            },
        ),
    ]
