# Generated by Django 4.2.6 on 2026-10-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_notification_balancealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactioncategory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='NULL only on manual rows that lock the transaction as uncategorized', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_assignments', to='finance.category'),
        ),
    ]
