# Generated by Django 4.2.6 on 2026-10-02 11:26

from django.db import migrations, models


def copy_account_to_accounts(apps, schema_editor):
    TransactionLimit = apps.get_model('finance', 'TransactionLimit')
    for limit in TransactionLimit.objects.all():
        limit.accounts.add(limit.account_id)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_usertransactioncategory_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionlimit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transactionlimit',
            name='accounts',
            field=models.ManyToManyField(related_name='limits', to='finance.account'),
        ),
        migrations.RunPython(
            copy_account_to_accounts, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='transactionlimit',
            name='account',
        ),
    ]
