# Generated by Django 4.2.6 on 2026-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_account_currency_eur_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='Transactions in this category are excluded from statistics (totals, chart, limits)'),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='excluded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='When set, this much of each matched transaction is excluded from statistics', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='usertransactioncategory',
            name='excluded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part of the amount this user does not count', max_digits=12),
        ),
    ]
