# Generated by Django 4.2.6 on 2026-10-06 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0017_seed_excluded_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOverviewShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='overview_shares', to='finance.account')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_overviews', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sharer', 'shared_with')},
            },
        ),
    ]
