# Generated by Django 4.2.6 on 2026-10-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_categoryoverviewshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='booked', help_text='Transactions-list group the entry came from: booked, pending, or any other group the API returns (Berlin Group spec also allows info). Non-booked rows are transient — replaced by the booked transaction once it settles', max_length=20),
        ),
    ]
