# Generated by Django 4.2.6 on 2026-10-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_apps', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'DROP TABLE IF EXISTS tv_archive_content',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DELETE FROM django_migrations WHERE app = 'tv_archive'",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
