# Generated by Django 4.2.6 on 2026-09-02 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Current access token (expires in ~1 hour)')),
                ('refresh_token', models.TextField(help_text='Refresh token (long-lasting, used to get new access tokens)')),
                ('token_expiry', models.DateTimeField(help_text='When the access token expires')),
                ('scopes', models.JSONField(default=list, help_text='List of granted OAuth scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google OAuth Credentials',
                'verbose_name_plural': 'Google OAuth Credentials',
            },
        ),
        migrations.DeleteModel(
            name='GoogleOAuth2Credentials',
        ),
    ]
