"""
Django settings for django_apps project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import json


BASE_DIR = Path(__file__).resolve().parent.parent

PRIVATE_SETTINGS_JSON_PATH = os.path.join(BASE_DIR, 'private_settings.json')

IS_GCP_ENVIRONMENT = (
    os.environ.get('GAE_APPLICATION') is not None
    or os.environ.get('K_SERVICE') is not None
    or os.environ.get('USE_GCP_SECRETS') == 'true'
)

if IS_GCP_ENVIRONMENT:
    import dj_database_url

    # Read secrets from environment variables (injected by Cloud Run)
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
    DEBUG = False
    BASE_URL = os.environ.get('APP_BASE_URL')
    ESV_KEY = os.environ.get('ESV_KEY')

    db_config = dj_database_url.parse(os.environ.get('DATABASE_URL'))
    db_config.setdefault('OPTIONS', {})
    db_config['OPTIONS']['sslmode'] = 'require'
    # Enable connection pooling to reuse DB connections
    db_config['CONN_MAX_AGE'] = 600  # 10 minutes
    DATABASES = {'default': db_config}

    GOOGLE_APP_SECRETS_PATH = '/tmp/app_secrets.json'
    if not os.path.exists(GOOGLE_APP_SECRETS_PATH):
        with open(GOOGLE_APP_SECRETS_PATH, 'w') as f:
            f.write(os.environ.get('GOOGLE_OAUTH_CLIENT_JSON', '{}'))

elif os.path.isfile(PRIVATE_SETTINGS_JSON_PATH):
    with open(PRIVATE_SETTINGS_JSON_PATH, 'r') as file:
        private_settings = json.load(file)
        SECRET_KEY = private_settings.get('SECRET_KEY')
        DEBUG = private_settings.get('DEBUG')
        BASE_URL = private_settings.get('BASE_URL')
        DATABASES = private_settings.get('DATABASES')
        ESV_KEY = private_settings.get('ESV_KEY')
    GOOGLE_APP_SECRETS_PATH = os.path.join(
        BASE_DIR, 'google_api', 'app_secrets.json'
    )
else:
    raise FileNotFoundError(
        'Private settings do not exist. '
        'Please provide private settings.'
    )

LOGIN_URL = '/login/'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = [
    'tedisrozenfelds.pythonanywhere.com',
    '127.0.0.1',
    '.vercel.app',
    'tedisrozenfelds.vercel.app',
    '.appspot.com',
    '.run.app',
]

# WSGI_APPLICATION = 'django_apps.wsgi.app'
WSGI_APPLICATION = 'django_apps.wsgi.application'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'django.contrib.staticfiles',
    'sslserver',
    'google_api',
    'google_tasks',
    'single_pages',
    'tv_archive',
    'bible_research',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://reactive-bible.vercel.app",
    "https://tedisrozenfelds.vercel.app",
]


# Allow all Vercel automatically deployed PR preview origins
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*-vincent-uches-projects\.vercel\.app$",
]

CORS_ALLOW_METHODS = (
    "GET",
    "POST",
)

ROOT_URLCONF = 'django_apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",  # project-wide templates folder
            BASE_DIR / "django_apps/templates",  # app templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

_PV = 'django.contrib.auth.password_validation'
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': f'{_PV}.UserAttributeSimilarityValidator'},
    {'NAME': f'{_PV}.MinimumLengthValidator'},
    {'NAME': f'{_PV}.CommonPasswordValidator'},
    {'NAME': f'{_PV}.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')
# collectstatic silently fails in Docker build (no private_settings.json
# available at build time), so STATIC_ROOT stays empty. WHITENOISE_USE_FINDERS
# tells WhiteNoise to also scan STATICFILES_DIRS (i.e. static/) directly,
# which IS committed to git and present in the container.
# Only use finders in DEBUG mode for better production performance
WHITENOISE_USE_FINDERS = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
print("MEDIA_ROOT: ", MEDIA_ROOT)


def create_log_handler(
    handler_name, level, filename=None,
    max_bytes=10485760, backup_count=10
):
    if DEBUG and filename:
        # Create logs directory if it doesn't exist
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)

        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': (
                '{levelname} {asctime} {module} '
                '{process:d} {thread:d} {message}'
            ),
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'tv_archive': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}
