"""
Django settings for django_apps project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import json


BASE_DIR = Path(__file__).resolve().parent.parent

PRIVATE_SETTINGS_JSON_PATH = os.path.join(BASE_DIR, 'private_settings.json')

if os.path.isfile(PRIVATE_SETTINGS_JSON_PATH):
    with open(PRIVATE_SETTINGS_JSON_PATH, 'r') as file:
        private_settings = json.load(file)
        SECRET_KEY = private_settings.get('SECRET_KEY')
        DEBUG = private_settings.get('DEBUG')
        BASE_URL = private_settings.get('BASE_URL')
        DATABASES = private_settings.get('DATABASES')
        ESV_KEY = private_settings.get('ESV_KEY')
else:
  raise FileNotFoundError(f'Private settings do not exist. Please provide private settings.')

ALLOWED_HOSTS = [
  'tedisrozenfelds.pythonanywhere.com',
  '127.0.0.1',
  '*.vercel.app',
]

# WSGI_APPLICATION = 'django_apps.wsgi.app'
WSGI_APPLICATION = 'django_apps.wsgi.application'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'django.contrib.staticfiles',
    'google_api',
    'single_pages',
    'tv_archive',
    'bible_research',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "*.vercel.app",
]

CORS_ALLOW_METHODS = (
    "GET",
    "POST",
)

ROOT_URLCONF = 'django_apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",  # If you have a project-wide templates folder
            BASE_DIR / "django_apps/templates",  # Add this line to include your app's templates directory
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = private_settings.get('DATABASES')

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'staticfiles')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
print("MEDIA_ROOT: ", MEDIA_ROOT)


def create_log_handler(handler_name, level, filename=None, max_bytes=10485760, backup_count=10):
    if DEBUG and filename:
        # Create logs directory if it doesn't exist
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)

        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'tv_archive': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}
