"""
Django settings for django_apps project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import json


BASE_DIR = Path(__file__).resolve().parent.parent

PRIVATE_SETTINGS_JSON_PATH = os.path.join(BASE_DIR, 'private_settings.json')


def _is_gcp_environment():
    return (
        os.environ.get('GAE_APPLICATION') is not None
        or os.environ.get('K_SERVICE') is not None
        or os.environ.get('USE_GCP_SECRETS') == 'true'
    )


def _is_vercel_environment():
    # Vercel exposes VERCEL=1 in both the build step and the
    # serverless function runtime.
    return os.environ.get('VERCEL') is not None


IS_GCP_ENVIRONMENT = _is_gcp_environment()
IS_VERCEL_ENVIRONMENT = _is_vercel_environment()
IS_CLOUD_ENVIRONMENT = IS_GCP_ENVIRONMENT or IS_VERCEL_ENVIRONMENT

if IS_CLOUD_ENVIRONMENT:
    import dj_database_url

    # Helper to ensure env vars are strings (defensive against bytes)
    def get_env_str(key, default=''):
        value = os.environ.get(key, default)
        if isinstance(value, bytes):
            return value.decode('utf-8')
        return value

    # Read secrets from environment variables (injected by Cloud Run
    # or configured in Vercel project settings)
    SECRET_KEY = get_env_str('DJANGO_SECRET_KEY')
    DEBUG = False
    BASE_URL = get_env_str('APP_BASE_URL')
    ESV_KEY = get_env_str('ESV_KEY')

    db_config = dj_database_url.parse(get_env_str('DATABASE_URL'))
    db_config.setdefault('OPTIONS', {})
    # sslmode/sslrootcert can be set via DATABASE_URL query params;
    # 'require' is only the default (Vercel needs e.g. verify-full
    # with the build-generated ca.pem).
    db_config['OPTIONS'].setdefault('sslmode', 'require')
    # Reuse DB connections where the process is long-lived. On Vercel
    # (serverless) each instance is a separate process, so persistent
    # connections hold Postgres slots open long after requests finish
    # and can exhaust Aiven's max_connections.
    db_config['CONN_MAX_AGE'] = 0 if IS_VERCEL_ENVIRONMENT else 600
    DATABASES = {'default': db_config}

    GOCARDLESS_SECRET_ID = get_env_str('GOCARDLESS_SECRET_ID')
    GOCARDLESS_SECRET_KEY = get_env_str('GOCARDLESS_SECRET_KEY')
    VAPID_PUBLIC_KEY = get_env_str('VAPID_PUBLIC_KEY')
    VAPID_PRIVATE_KEY = get_env_str('VAPID_PRIVATE_KEY')
    VAPID_SUBJECT = get_env_str('VAPID_SUBJECT')

    GOOGLE_APP_SECRETS_PATH = '/tmp/app_secrets.json'
    if not os.path.exists(GOOGLE_APP_SECRETS_PATH):
        with open(GOOGLE_APP_SECRETS_PATH, 'w') as f:
            f.write(get_env_str('GOOGLE_OAUTH_CLIENT_JSON', '{}'))

elif os.path.isfile(PRIVATE_SETTINGS_JSON_PATH):
    with open(PRIVATE_SETTINGS_JSON_PATH, 'r') as file:
        private_settings = json.load(file)
        SECRET_KEY = private_settings.get('SECRET_KEY')
        DEBUG = private_settings.get('DEBUG')
        BASE_URL = private_settings.get('BASE_URL')
        DATABASES = private_settings.get('DATABASES')
        ESV_KEY = private_settings.get('ESV_KEY')
        GOCARDLESS_SECRET_ID = private_settings.get(
            'GOCARDLESS_SECRET_ID'
        )
        GOCARDLESS_SECRET_KEY = private_settings.get(
            'GOCARDLESS_SECRET_KEY'
        )
        VAPID_PUBLIC_KEY = private_settings.get('VAPID_PUBLIC_KEY', '')
        VAPID_PRIVATE_KEY = private_settings.get(
            'VAPID_PRIVATE_KEY', ''
        )
        VAPID_SUBJECT = private_settings.get('VAPID_SUBJECT', '')
    GOOGLE_APP_SECRETS_PATH = os.path.join(
        BASE_DIR, 'google_api', 'app_secrets.json'
    )
else:
    # Local fallback when neither GCP env vars nor
    # private_settings.json are available (fresh clones, CI).
    # Uses safe dev defaults so manage.py commands still work.
    import warnings
    warnings.warn(
        'private_settings.json not found and no GCP environment '
        'detected - falling back to insecure local dev defaults '
        '(sqlite db.sqlite3, DEBUG=True).'
    )
    SECRET_KEY = os.environ.get(
        'DJANGO_SECRET_KEY', 'dev-only-insecure-secret-key'
    )
    DEBUG = os.environ.get('DEBUG', 'true').lower() in (
        'true', '1', 'yes'
    )
    BASE_URL = os.environ.get('APP_BASE_URL', 'http://127.0.0.1:8000')
    db_url = os.environ.get('DATABASE_URL')
    if db_url:
        import dj_database_url
        DATABASES = {'default': dj_database_url.parse(db_url)}
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
    ESV_KEY = os.environ.get('ESV_KEY', '')
    GOCARDLESS_SECRET_ID = os.environ.get('GOCARDLESS_SECRET_ID', '')
    GOCARDLESS_SECRET_KEY = os.environ.get('GOCARDLESS_SECRET_KEY', '')
    VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
    VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
    VAPID_SUBJECT = os.environ.get('VAPID_SUBJECT', '')
    GOOGLE_APP_SECRETS_PATH = os.path.join(
        BASE_DIR, 'google_api', 'app_secrets.json'
    )

LOGIN_URL = '/login/'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = [
    'tedisrozenfelds.pythonanywhere.com',
    '127.0.0.1',
    'localhost',
    '.vercel.app',
    'tedisrozenfelds.vercel.app',
    '.appspot.com',
    '.run.app',
]

# WSGI_APPLICATION = 'django_apps.wsgi.app'
WSGI_APPLICATION = 'django_apps.wsgi.application'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'django.contrib.staticfiles',
    'django_vite',
    'ninja',
    'sslserver',
    'google_api',
    'google_tasks',
    'finance',
    'single_pages',
    'tv_archive',
    'bible_research',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://reactive-bible.vercel.app",
    "https://tedisrozenfelds.vercel.app",
]


# Allow all Vercel automatically deployed PR preview origins
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*-vincent-uches-projects\.vercel\.app$",
]

CORS_ALLOW_METHODS = (
    "GET",
    "POST",
)

ROOT_URLCONF = 'django_apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",  # project-wide templates folder
            BASE_DIR / "django_apps/templates",  # app templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

_PV = 'django.contrib.auth.password_validation'
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': f'{_PV}.UserAttributeSimilarityValidator'},
    {'NAME': f'{_PV}.MinimumLengthValidator'},
    {'NAME': f'{_PV}.CommonPasswordValidator'},
    {'NAME': f'{_PV}.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
# frontend_dist/ is generated at build time (gitignored), so filter
# the list to directories that exist — otherwise `manage.py check`
# warns (staticfiles.W004) on every fresh checkout.
STATICFILES_DIRS = [
    p for p in (
        os.path.join(BASE_DIR, 'static'),
        os.path.join(BASE_DIR, 'frontend_dist'),
    ) if os.path.isdir(p)
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')
# collectstatic silently fails in Docker build (no private_settings.json
# available at build time), so STATIC_ROOT stays empty. WHITENOISE_USE_FINDERS
# tells WhiteNoise to also scan STATICFILES_DIRS (i.e. static/) directly,
# which IS committed to git and present in the container.
# Only use finders in DEBUG mode for better production performance
WHITENOISE_USE_FINDERS = DEBUG
# Vite emits content-hashed names (e.g. tasks/tasks.<hash>.js) whose
# hashes are base64url — they include - and _, so [0-9a-f] is not
# enough. Without this, hashed assets fall back to whitenoise's short
# default max-age and get revalidated on every page load.
WHITENOISE_IMMUTABLE_FILE_TEST = r'\.[0-9A-Za-z_-]{8}\.'

# React frontend (frontend/, built by Vite into frontend_dist/).
# VITE_DEV=1 + `npm run dev --prefix frontend` enables the dev
# server + HMR; otherwise entries resolve via manifest.json.
DJANGO_VITE = {
    'default': {
        'dev_mode': DEBUG and os.environ.get('VITE_DEV') == '1',
        # Non-default port so another project's vite on :5173 can't
        # shadow these dev-asset URLs — must match server.port in
        # frontend/vite.config.ts (both honor VITE_PORT).
        'dev_server_port': int(os.environ.get('VITE_PORT', '5273')),
        'static_url_prefix': '',
        'manifest_path': os.path.join(
            BASE_DIR, 'frontend_dist', 'manifest.json'
        ),
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


def create_log_handler(
    handler_name, level, filename=None,
    max_bytes=10485760, backup_count=10
):
    if DEBUG and filename:
        # Create logs directory if it doesn't exist
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)

        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': (
                '{levelname} {asctime} {module} '
                '{process:d} {thread:d} {message}'
            ),
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'tv_archive': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}
