# Generated by Django 4.2.6 on 2026-08-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0002_googletask_starred_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletask',
            name='local_labels',
        ),
        migrations.DeleteModel(
            name='TaskLabel',
        ),
    ]
