# Generated by Django 4.2.6 on 2026-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0003_remove_googletask_local_labels_delete_tasklabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googletask',
            options={'ordering': [models.OrderBy(models.F('task_order'), nulls_last=True), '-updated']},
        ),
        migrations.AddField(
            model_name='googletask',
            name='task_order',
            field=models.PositiveIntegerField(blank=True, help_text='Manual ordering within task list', null=True),
        ),
    ]
