# Generated by Django 4.2.6 on 2026-08-05 16:02

from django.db import migrations, models


def copy_starred_order_to_task_order(apps, schema_editor):
    """
    Copy starred_order values to task_order for tasks that have
    starred_order but no task_order.
    """
    GoogleTask = apps.get_model('google_tasks', 'GoogleTask')

    # Update tasks that have starred_order but no task_order
    tasks_to_update = GoogleTask.objects.filter(
        starred_order__isnull=False,
        task_order__isnull=True
    )

    for task in tasks_to_update:
        task.task_order = task.starred_order
        task.save(update_fields=['task_order'])


def reverse_copy(apps, schema_editor):
    """
    Reverse migration: copy task_order back to starred_order.
    """
    GoogleTask = apps.get_model('google_tasks', 'GoogleTask')

    tasks_to_update = GoogleTask.objects.filter(
        task_order__isnull=False,
        starred_order__isnull=True
    )

    for task in tasks_to_update:
        task.starred_order = task.task_order
        task.save(update_fields=['starred_order'])


class Migration(migrations.Migration):

    dependencies = [
        (
            'google_tasks',
            '0004_alter_googletask_options_googletask_task_order'
        ),
    ]

    operations = [
        migrations.RunPython(
            copy_starred_order_to_task_order,
            reverse_copy
        ),
        migrations.RemoveField(
            model_name='googletask',
            name='starred_order',
        ),
        migrations.AlterField(
            model_name='googletask',
            name='task_order',
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    'Manual ordering for tasks (replaces starred_order)'
                ),
                null=True
            ),
        ),
    ]
