# Generated by Django 4.2.6 on 2026-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0005_migrate_starred_order_to_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletask',
            name='is_divider',
            field=models.BooleanField(default=False, help_text='If True, this task acts as a visual divider'),
        ),
    ]
