# Generated by Django 4.2.6 on 2026-08-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0006_add_is_divider_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the task was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='googletask',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Task is archived (hidden from main view but accessible)'),
        ),
        migrations.AddField(
            model_name='googletask',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Task is in trash (will be auto-purged after 30 days)'),
        ),
    ]
