# Generated by Django 4.2.6 on 2026-08-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0007_googletask_deleted_at_googletask_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletask',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='google_tasks.googletasklist'),
        ),
    ]
