# Generated by Django 4.2.6 on 2026-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0008_alter_googletask_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletask',
            name='reminder_date',
            field=models.DateTimeField(blank=True, help_text='Reminder date and time for the task', null=True),
        ),
    ]
