# Generated by Django 4.2.6 on 2026-08-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0009_googletask_reminder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletask',
            name='reminder_date',
        ),
    ]
