# Generated by Django 4.2.6 on 2026-08-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0010_remove_googletask_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletask',
            name='created',
            field=models.DateTimeField(blank=True, help_text='When this task was first synced/created locally', null=True),
        ),
    ]
