# Generated by Django 4.2.6 on 2026-08-25 06:40

from django.db import migrations


def populate_created_field(apps, schema_editor):
    """
    Populate created field for existing tasks.
    Use updated field as fallback.
    """
    GoogleTask = apps.get_model('google_tasks', 'GoogleTask')

    tasks_to_update = GoogleTask.objects.filter(created__isnull=True)
    for task in tasks_to_update:
        task.created = task.updated if task.updated else None

    GoogleTask.objects.bulk_update(
        tasks_to_update, ['created'], batch_size=500
    )


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0011_googletask_created'),
    ]

    operations = [
        migrations.RunPython(
            populate_created_field,
            reverse_code=migrations.RunPython.noop
        ),
    ]
