# Generated by Django 4.2.6 on 2026-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0012_populate_created_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletask',
            name='starred_order',
            field=models.PositiveIntegerField(blank=True, help_text='Manual ordering for starred tasks in starred view', null=True),
        ),
        migrations.AlterField(
            model_name='googletask',
            name='task_order',
            field=models.PositiveIntegerField(blank=True, help_text='Manual ordering for tasks in task list view', null=True),
        ),
    ]
