# Generated by Django 4.2.6 on 2026-09-19 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_tasks', '0013_googletask_starred_order_alter_googletask_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletask',
            name='starred_order',
            field=models.PositiveIntegerField(default=1, help_text='Manual ordering for starred tasks in starred view'),
        ),
        migrations.AlterField(
            model_name='googletask',
            name='task_order',
            field=models.PositiveIntegerField(default=1, help_text='Manual ordering for tasks in task list view'),
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#0d6efd', help_text='Hex color code for label badge', max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='googletask',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='google_tasks.tasklabel'),
        ),
    ]
