# Generated by Django 4.2.6 on 2026-09-19 14:14

from django.db import migrations


def populate_task_labels(apps, schema_editor):
    """
    Create TaskLabel for each GoogleTaskList and assign labels to tasks.
    """
    GoogleTaskList = apps.get_model('google_tasks', 'GoogleTaskList')
    GoogleTask = apps.get_model('google_tasks', 'GoogleTask')
    TaskLabel = apps.get_model('google_tasks', 'TaskLabel')

    # Create TaskLabel for each GoogleTaskList
    label_map = {}
    for task_list in GoogleTaskList.objects.all():
        label, created = TaskLabel.objects.get_or_create(
            user=task_list.user,
            name=task_list.title,
            defaults={'color': '#0d6efd'}
        )
        label_map[task_list.id] = label

    # Assign labels to tasks based on current task_list
    # Use through model for bulk operations
    GoogleTaskLabels = GoogleTask.labels.through
    relations_to_create = []

    for task in GoogleTask.objects.select_related('task_list').all():
        if task.task_list and task.task_list.id in label_map:
            relations_to_create.append(
                GoogleTaskLabels(
                    googletask_id=task.id,
                    tasklabel_id=label_map[task.task_list.id].id
                )
            )

    # Bulk create all relations at once
    if relations_to_create:
        GoogleTaskLabels.objects.bulk_create(
            relations_to_create,
            ignore_conflicts=True
        )


def reverse_populate_task_labels(apps, schema_editor):
    """
    Remove all TaskLabels (reverse migration).
    """
    TaskLabel = apps.get_model('google_tasks', 'TaskLabel')
    TaskLabel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0014_alter_googletask_starred_order_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_task_labels,
            reverse_populate_task_labels
        ),
    ]
