# Generated by Django 4.2.6 on 2026-09-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_tasks', '0015_populate_task_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletask',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When we last synced this task with Google Tasks', null=True),
        ),
        migrations.AddField(
            model_name='googletask',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='When this task was last modified in our database', null=True),
        ),
        migrations.AlterField(
            model_name='googletask',
            name='updated',
            field=models.DateTimeField(blank=True, help_text='Last update timestamp from Google Tasks API', null=True),
        ),
    ]
