# Generated by Django 4.2.6 on 2026-10-06 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sender_pattern', models.CharField(help_text='Matched against the raw From header (e.g. "e-klase <notifikacijas@e-klase.lv>"), case-insensitive', max_length=255)),
                ('sender_match_type', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with')], default='contains', max_length=20)),
                ('force_language', models.CharField(blank=True, choices=[('lv', 'Latvian'), ('en', 'English')], default='', help_text='Pin the audio language instead of auto-detecting it; returned as the message "lang" hint', max_length=2)),
                ('subject_regex', models.TextField(blank=True, default='', help_text='First capture group replaces the subject (e.g. "Tēma: (.*?)(?=No:)")')),
                ('body_regex', models.TextField(blank=True, default='', help_text='First capture group replaces the parsed body')),
                ('strip_patterns', models.JSONField(blank=True, default=list, help_text='List of regexes removed from the extracted body via re.sub with re.DOTALL (headers, footers, attachment lines); whitespace is collapsed afterwards')),
                ('include_subject', models.BooleanField(default=True)),
                ('include_sender', models.BooleanField(default=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_parsing_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'pk'],
            },
        ),
    ]
